sudo: false
language: "node_js"
node_js:
  - "4"
  - "6"
  - "8"
  - "9"
env:
  - INSTALL_CMD="npm install"
  - INSTALL_CMD="yarn install"
script:
  - ${INSTALL_CMD}
  - npm run coverage
  - eslint --max-warnings 0 .
after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls
