sudo: false
language: "node_js"
node_js:
  - "4"
  - "5"
before_script:
  - npm install standard
  - standard
script:
  - npm install istanbul
  - istanbul cover ./node_modules/.bin/_mocha --report lcovonly
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls